### PR TITLE
Support downloading profiles

### LINKED ISSUE #64: Allow download pprof profiles for offline use

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <yb532204897@gmail.com>

Fixes #64 

Add an API for downloading, almost the same as the /pprof API.

### CODE REVIEW

**Comment by yeya24** [comment]
This API can be added to the data source.

image

**Comment by brancz** [comment]
Any way we can embed this into the conprof UI itself as well? :)

**Comment by yeya24** [comment]
@brancz This pr only adds the API. I want to add it to the UI as well but I cannot find a good place to add a download button for each sample.

**Comment by bwplotka** [comment]
Amazing!

**Comment by bboreham** [comment]
It wasn't immediately obvious to me, so I'm writing it here for the next person:
Given a profile in the browser with url `.../pprof/longhashstring/...`, replace `/pprof/` with `/download/` in the url to get the raw data.

**Pull request merged**
